#!/usr/bin/perl
$tkfst = $ENV{'DARTDIR'} . "/src/indiegram/tkfst.cc";
for $parse ("alignments/0.1/13.reference.parse", "inferred/0.1/13.indiegram.parse") {
open IN, "<$parse" or die;
open OUT, ">$parse.inits";
print OUT "// $parse.inits: generated by $0 from $parse and $tkfst\n\n";
while(<IN>){chomp;if(/^\s*\(?([^\(\);\s]+)/){$y=$1; if ( defined$x ) {($a,$b)=($y=~/end/)?($y,$x):($x,$y);mysys("egrep '^[^M]*transition_scores".(($a=~/start|end/)?"[^M]*$a\[^M]*$b":"\\.transition \\($a, $b\\)")."' $tkfst")}
if(/\(?(\S+).*\->\s+(\S+)\s+(\S+)/){mysys("egrep \"init_bifurc.*$1.*$2.*$3\" $tkfst");$x=undef}else{$x=$y eq"end"?undef:$y}
}}
sub mysys { my$c=shift;
print OUT "// $c\n",`$c`,"\n";
#print OUT `$c`;
}
close IN;
close OUT or die;
}
